# Generated by Django 5.2.8 on 2025-11-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JSONDataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('database_type', models.CharField(choices=[('SQL', 'PostgreSQL'), ('NoSQL', 'MongoDB')], max_length=10)),
                ('confidence_score', models.IntegerField(help_text='AI confidence in DB choice (0-100)')),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inferred_schema', models.JSONField(default=dict)),
                ('sample_data', models.JSONField(blank=True, default=dict)),
                ('structure_depth', models.IntegerField(default=0)),
                ('has_nested_objects', models.BooleanField(default=False)),
                ('has_arrays', models.BooleanField(default=False)),
                ('is_consistent', models.BooleanField(default=True)),
                ('ai_reasoning', models.TextField(blank=True, null=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['database_type'], name='storage_jso_databas_718e9d_idx'), models.Index(fields=['created_at'], name='storage_jso_created_25128b_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('detected_type', models.CharField(help_text='Primary file category', max_length=50)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_extension', models.CharField(max_length=20)),
                ('magic_description', models.TextField(blank=True, null=True)),
                ('ai_category', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_tags', models.JSONField(blank=True, default=list)),
                ('ai_description', models.TextField(blank=True, null=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('storage_category', models.CharField(max_length=100)),
                ('storage_subcategory', models.CharField(max_length=100)),
                ('relative_path', models.CharField(max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['detected_type'], name='storage_med_detecte_92252d_idx'), models.Index(fields=['storage_category'], name='storage_med_storage_e98a92_idx'), models.Index(fields=['uploaded_at'], name='storage_med_uploade_cd3334_idx')],
            },
        ),
    ]
