# Generated by Django 5.2.8 on 2025-11-15 07:11

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='The search query')),
                ('query_embedding', pgvector.django.vector.VectorField(dimensions=768, help_text='Vector embedding of the query')),
                ('results_count', models.IntegerField(default=0)),
                ('top_result_score', models.FloatField(blank=True, null=True)),
                ('user_session', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='storage_sea_created_c6c709_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='Position of this chunk in the document')),
                ('chunk_text', models.TextField(help_text='The actual text content of this chunk')),
                ('chunk_size', models.IntegerField(help_text='Number of characters in this chunk')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, help_text='Vector embedding generated by Ollama nomic-embed-text model')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_type', models.CharField(help_text='File type/category', max_length=50)),
                ('page_number', models.IntegerField(blank=True, help_text='Page number (for PDFs)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (author, date, tags, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.ForeignKey(blank=True, help_text='Reference to the source media file (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='storage.mediafile')),
            ],
            options={
                'ordering': ['media_file', 'chunk_index'],
                'indexes': [models.Index(fields=['file_name'], name='storage_doc_file_na_d694ab_idx'), models.Index(fields=['file_type'], name='storage_doc_file_ty_aeeaaa_idx'), models.Index(fields=['created_at'], name='storage_doc_created_b339f4_idx')],
            },
        ),
    ]
